os: linux
language: node_js
node_js:
  - 10
  - 'stable'
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - yarn build
jobs:
  include:
    - stage: release to gh-pages
      script:
        - echo "Deploying to GitHub pages ..."
        - yarn deploy
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        local_dir: out # deployment folder
        target_branch: gh-pages
        keep_history: false # force push
        on:
          branch: master
          tags: true
